project:
  type: website
  output-dir: docs

website:
  title: "Audrey Tsung"
  favicon: images/favicon.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: blog.qmd
        text: Blog

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true



